import {
  Controller,
  Post,
  Body,
  Headers,
  Req,
  RawBodyRequest,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiHeader } from '@nestjs/swagger';
import { Request } from 'express';
import { Public } from '../auth/decorators/public.decorator';
import { WebhooksService } from './webhooks.service';
import { GitHubAppWebhookService } from './services/github-app-webhook.service';
import { GitHubActionsWebhookDto } from './dto/github-actions-webhook.dto';
import { AlertsWebhookService } from './services/alerts-webhook.service';
import {
  AlertmanagerWebhookDto,
  AlertsWebhookResultDto,
} from './dto/alertmanager-webhook.dto';

@ApiTags('Webhooks')
@Controller('webhooks')
export class WebhooksController {
  constructor(
    private readonly webhooksService: WebhooksService,
    private readonly githubAppWebhookService: GitHubAppWebhookService,
    private readonly alertsWebhookService: AlertsWebhookService,
  ) {}

  @Post('alerts')
  @Public()
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Receive Alertmanager notifications',
    description:
      'Called in-cluster by Alertmanager after grouping, deduplication and inhibition. ' +
      'Flui resolves each alert to its application or node. Authenticated via X-Flui-Token.',
  })
  @ApiHeader({
    name: 'X-Flui-Token',
    description: 'Shared secret configured as ALERTS_WEBHOOK_TOKEN',
    required: true,
  })
  @ApiResponse({ status: 200, type: AlertsWebhookResultDto })
  @ApiResponse({ status: 401, description: 'Invalid or missing token' })
  async handleAlerts(
    @Headers('x-flui-token') token: string,
    @Headers('authorization') authorization: string,
    @Body() dto: AlertmanagerWebhookDto,
  ): Promise<AlertsWebhookResultDto> {
    return this.alertsWebhookService.handle(
      { header: token, authorization },
      dto,
    );
  }

  @Post('github-actions')
  @Public()
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Receive GitHub Actions build completion notification',
    description:
      'Called by the Flui-generated GitHub Actions workflow after a build succeeds or fails. Authenticated via X-Flui-Token header.',
  })
  @ApiHeader({
    name: 'X-Flui-Token',
    description: 'Per-application webhook token generated by Flui',
    required: true,
  })
  @ApiResponse({ status: 200, description: 'Webhook processed' })
  @ApiResponse({ status: 401, description: 'Invalid or missing token' })
  async handleGitHubActions(
    @Headers('x-flui-token') token: string,
    @Body() dto: GitHubActionsWebhookDto,
  ): Promise<{ received: boolean }> {
    return this.webhooksService.handleGitHubActionsWebhook(token, dto);
  }

  @Post('github-app')
  @Public()
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Receive GitHub App webhook events',
    description:
      'Called by GitHub when the Flui GitHub App receives events (installation, workflow_run, push). ' +
      'Validated via x-hub-signature-256 HMAC header.',
  })
  @ApiHeader({
    name: 'x-github-event',
    description: 'GitHub event type',
    required: true,
  })
  @ApiHeader({
    name: 'x-hub-signature-256',
    description: 'HMAC-SHA256 signature of the payload',
    required: true,
  })
  @ApiResponse({ status: 200, description: 'Webhook processed' })
  @ApiResponse({ status: 401, description: 'Invalid signature' })
  async handleGitHubApp(
    @Headers('x-github-event') event: string,
    @Headers('x-hub-signature-256') signature: string,
    @Req() req: RawBodyRequest<Request>,
    @Body() payload: any,
  ): Promise<{ received: boolean }> {
    const rawBody = req.rawBody ?? Buffer.from(JSON.stringify(payload));
    await this.githubAppWebhookService.validateSignature(rawBody, signature);
    return this.githubAppWebhookService.handleEvent(
      event,
      payload.action,
      payload,
    );
  }
}
