import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
} from 'typeorm';

@Entity('ssh_keys')
export class SSHKeyEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  name: string;

  @Column()
  publicKey: string;

  @Column()
  fingerprint: string;

  @Column()
  keyPath: string;

  /** The private half, sealed with SSH_KEY_ENCRYPTION_KEY; null on rows written before it was kept here. */
  @Column({ type: 'text', nullable: true })
  sealedPrivateKey: string | null;

  @Column({ default: 'ed25519' })
  type: 'ed25519' | 'rsa';

  @Column({ default: true })
  isActive: boolean;

  @Column({ default: false })
  autoGenerated: boolean;

  @Column({ nullable: true })
  lastUsed: Date;

  @Column({
    type: 'jsonb',
    nullable: true,
    default: {},
    comment:
      'Key-value pairs for tagging. Values can be strings or arrays (e.g., cluster-id: ["cluster1", "cluster2"], cluster-node-id: "node1")',
  })
  tags: Record<string, string | string[]>;

  @Column({
    type: 'jsonb',
    nullable: true,
    default: {},
    comment:
      'Mapping of cloud provider to provider-specific SSH key IDs (e.g., { "HETZNER": "12345", "CONTABO": "abc-def" })',
  })
  providerKeyMappings: Record<string, string>;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt: Date;
}
