import {
  Controller,
  Post,
  Get,
  HttpCode,
  HttpStatus,
  Query,
  Body,
  UseGuards,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiQuery,
  ApiBearerAuth,
} from '@nestjs/swagger';
import { AdminGuard } from '../../auth/guards/admin.guard';
import { Admin } from '../../auth/decorators/admin.decorator';
import { CAManagerService } from '../services/ca-manager.service';
import { CertificateSignerService } from '../services/certificate-signer.service';
import { CAPublicKeyDto } from '../dto/ca-public-key.dto';
import { RegisterCADto, RegisterCAResponseDto } from '../dto/register-ca.dto';

@ApiTags('CA Management')
@ApiBearerAuth()
@Controller('access/ca')
export class CAController {
  constructor(
    private readonly caManager: CAManagerService,
    private readonly certificateSigner: CertificateSignerService,
  ) {}

  // An installation-bootstrap route, still gated on the boolean: the same
  // credential also writes clusters and firewalls, so a `platform:bootstrap`
  // permission here alone would break `flui env create` halfway through.
  @Post('initialize')
  @UseGuards(AdminGuard)
  @Admin()
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({ summary: 'Initialize CA keypair (admin only)' })
  @ApiResponse({
    status: 201,
    description: 'CA initialized successfully',
    type: CAPublicKeyDto,
  })
  @ApiResponse({
    status: 409,
    description: 'CA already exists',
  })
  async initializeCA(): Promise<CAPublicKeyDto> {
    const ca = await this.caManager.initializeCA();
    return {
      publicKey: ca.publicKey,
      fingerprint: ca.fingerprint,
      type: ca.type,
      createdAt: ca.createdAt,
      expiresAt: ca.expiresAt,
    };
  }

  @Post('register')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Register external CA public key from CLI',
    description:
      'Registers an external CA public key (generated by CLI). Only stores the public key, no private key is transmitted or stored.',
  })
  @ApiResponse({
    status: 201,
    description: 'CA registered successfully',
    type: RegisterCAResponseDto,
  })
  @ApiResponse({
    status: 400,
    description: 'Invalid public key format',
  })
  @ApiResponse({
    status: 409,
    description: 'CA already exists',
  })
  async registerCA(@Body() dto: RegisterCADto): Promise<RegisterCAResponseDto> {
    const ca = await this.caManager.registerExternalCA(dto.publicKey, {
      name: dto.name,
      replace: dto.replace,
      metadata: dto.metadata,
    });

    return {
      id: ca.id,
      name: ca.name,
      publicKey: ca.publicKey,
      fingerprint: ca.fingerprint,
      type: ca.type,
      createdAt: ca.createdAt,
      expiresAt: ca.expiresAt,
      message: dto.replace
        ? 'CA replaced successfully'
        : 'CA registered successfully',
    };
  }

  @Get('info')
  @ApiOperation({ summary: 'Get CA info (without private key)' })
  @ApiResponse({
    status: 200,
    description: 'CA info retrieved',
    type: CAPublicKeyDto,
  })
  @ApiResponse({
    status: 404,
    description: 'No active CA found',
  })
  async getCAInfo(): Promise<CAPublicKeyDto> {
    const ca = await this.caManager.getCAInfo();
    return {
      publicKey: ca.publicKey,
      fingerprint: ca.fingerprint,
      type: ca.type,
      createdAt: ca.createdAt,
      expiresAt: ca.expiresAt,
    };
  }

  @Get('enrollment-script')
  @ApiOperation({ summary: 'Get server enrollment script' })
  @ApiResponse({
    status: 200,
    description: 'Enrollment script generated successfully',
    schema: {
      type: 'object',
      properties: {
        script: {
          type: 'string',
          description: 'Bash script for server enrollment',
        },
      },
    },
  })
  async getEnrollmentScript(): Promise<{ script: string }> {
    const script = await this.caManager.getEnrollmentScript();
    return { script };
  }

  @Post('test-certificate')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Generate ephemeral certificate for testing (DEV ONLY)',
    description:
      'Generates an ephemeral certificate for manual SSH testing. Returns private key and certificate that can be used with ssh command line.',
  })
  @ApiQuery({
    name: 'ttl',
    required: false,
    type: Number,
    description: 'Certificate TTL in seconds (default: 180)',
    example: 180,
  })
  @ApiResponse({
    status: 200,
    description: 'Certificate generated successfully',
    schema: {
      type: 'object',
      properties: {
        privateKey: {
          type: 'string',
          description: 'ED25519 private key (PEM format)',
        },
        certificate: {
          type: 'string',
          description: 'SSH certificate signed by CA',
        },
        expiresAt: {
          type: 'string',
          format: 'date-time',
          description: 'Certificate expiration time',
        },
        principals: {
          type: 'array',
          items: { type: 'string' },
          description: 'Valid principals (usernames)',
        },
        instructions: {
          type: 'string',
          description: 'Command line usage instructions',
        },
      },
    },
  })
  async generateTestCertificate(@Query('ttl') ttl = 180) {
    const ttlSeconds = ttl;
    const cert = await this.certificateSigner.generateEphemeralCertificate(
      'test',
      ttlSeconds,
    );

    const expiresAt = new Date(Date.now() + ttlSeconds * 1000);

    return {
      privateKey: cert.privateKey,
      certificate: cert.certificate,
      expiresAt: expiresAt.toISOString(),
      principals: ['root', 'ubuntu', 'admin'],
      instructions: `
# How to use this certificate for SSH testing on Windows:

# 1. Save the private key and certificate to files:
echo "${cert.privateKey.replaceAll('n', '\n')}" > ephemeral_key
echo "${cert.certificate.replaceAll('n', '\n')}" > ephemeral_key-cert.pub

# 2. Set correct permissions (Git Bash):
chmod 600 ephemeral_key
chmod 644 ephemeral_key-cert.pub

# 3. Connect to your server:
ssh -i ephemeral_key root@YOUR_SERVER_IP

# Certificate expires at: ${expiresAt.toISOString()}
# Valid for principals: root, ubuntu, admin
# TTL: ${ttlSeconds} seconds (${Math.floor(ttlSeconds / 60)} minutes)

# Note: The certificate file MUST be named <keyfile>-cert.pub
# SSH automatically looks for the certificate file when you specify the key.
      `.trim(),
    };
  }
}
