import {
  Controller,
  Get,
  Post,
  Delete,
  Patch,
  Body,
  Param,
  Query,
  Request,
  Res,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { Response } from 'express';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiQuery,
  ApiParam,
  ApiBearerAuth,
} from '@nestjs/swagger';
import { RequireSection } from '../iam/decorators/require-section.decorator';
import { SECTION } from '../iam/constants/iam-sections';
import { AccessService } from './services/access.service';
import { CreateSSHKeyDto } from './dto/create-ssh-key.dto';
import { BearerTokenDto } from './dto/bearer-token.dto';
import { CreateBearerTokenDto } from './dto/create-bearer-token.dto';
import { ProviderRefreshTokenDto } from './dto/refresh-token.dto';
import { CreateApiTokenDto } from './dto/create-api-token.dto';
import { ApiTokenDto } from './dto/api-token.dto';
import { SSHKeyDto } from './dto/ssh-key.dto';
import { UpdateSSHKeyDto } from './dto/update-ssh-key.dto';
import { CloudProvider } from '../providers/enums/cloud-provider.enum';

@ApiTags('Access Management')
@ApiBearerAuth()
@Controller('access')
export class AccessController {
  constructor(private readonly accessService: AccessService) {}

  @Get('ssh-keys')
  @ApiOperation({
    summary: 'List SSH keys',
    description:
      'Returns SSH keys from local database and optionally from cloud provider. Can filter by tags like cluster-id and cluster_node_id. Supports array values for filtering multiple clusters.',
  })
  @ApiQuery({
    name: 'provider',
    enum: CloudProvider,
    required: false,
    description: 'Include SSH keys from specific cloud provider',
  })
  @ApiQuery({
    name: 'cluster-id',
    required: false,
    description:
      'Filter SSH keys by cluster ID tag. Can be a single value or comma-separated list',
    example: 'k3s-prod-eu-001,k3s-prod-eu-002',
  })
  @ApiQuery({
    name: 'cluster-node-id',
    required: false,
    description: 'Filter SSH keys by cluster node ID tag',
    example: 'node-master-01',
  })
  @ApiQuery({
    name: 'auto-generated',
    required: false,
    description:
      'Filter by auto-generated keys only (keys automatically created by the system)',
    example: 'true',
  })
  @ApiResponse({
    status: 200,
    description: 'Returns all SSH keys from database and provider',
    type: [SSHKeyDto],
  })
  async listSSHKeys(
    @Query('provider') provider?: CloudProvider,
    @Query('cluster-id') clusterId?: string,
    @Query('cluster-node-id') clusterNodeId?: string,
    @Query('auto-generated') autoGenerated?: string,
  ) {
    // Build tag filters object
    const tagFilters: Record<string, string | string[]> = {};

    if (clusterId) {
      // Support both single values and comma-separated multiple values
      if (clusterId.includes(',')) {
        tagFilters['cluster-id'] = clusterId.split(',').map((id) => id.trim());
      } else {
        tagFilters['cluster-id'] = clusterId;
      }
    }

    if (clusterNodeId) {
      tagFilters['cluster-node-id'] = clusterNodeId;
    }

    if (autoGenerated === 'true') {
      tagFilters['auto-generated'] = 'true';
    }

    return this.accessService.listSSHKeys(provider, tagFilters);
  }

  @Post('ssh-keys')
  @ApiOperation({ summary: 'Add SSH key' })
  @ApiResponse({
    status: 201,
    description: 'SSH key created and synced to all providers successfully',
    type: SSHKeyDto,
  })
  @ApiResponse({
    status: 207,
    description:
      'SSH key created but one or more provider syncs failed. Check syncErrors in response body.',
    type: SSHKeyDto,
  })
  async addSSHKey(
    @Request() req,
    @Body() createSSHKeyDto: CreateSSHKeyDto,
    @Res({ passthrough: true }) res: Response,
  ) {
    const result = await this.accessService.addSSHKey(createSSHKeyDto);
    if (result.syncErrors && Object.keys(result.syncErrors).length > 0) {
      res.status(HttpStatus.MULTI_STATUS);
    } else {
      res.status(HttpStatus.CREATED);
    }
    return result;
  }

  @Patch('ssh-keys/:id')
  @ApiOperation({
    summary: 'Update SSH key',
    description:
      'Update SSH key tags, providerKeyMappings, or trigger sync to additional providers via syncProviders. ' +
      'Tags are completely replaced, not merged.',
  })
  @ApiParam({
    name: 'id',
    description: 'SSH key ID',
    type: 'string',
    example: '123e4567-e89b-12d3-a456-426614174000',
  })
  @ApiResponse({
    status: 200,
    description: 'SSH key updated successfully',
    type: SSHKeyDto,
  })
  @ApiResponse({
    status: 207,
    description:
      'Update applied but one or more provider syncs failed. Check syncErrors in response body.',
    type: SSHKeyDto,
  })
  @ApiResponse({ status: 404, description: 'SSH key not found' })
  async updateSSHKey(
    @Param('id') id: string,
    @Body() updateSSHKeyDto: UpdateSSHKeyDto,
    @Res({ passthrough: true }) res: Response,
  ) {
    const result = await this.accessService.updateSSHKey(id, updateSSHKeyDto);
    if (result.syncErrors && Object.keys(result.syncErrors).length > 0) {
      res.status(HttpStatus.MULTI_STATUS);
    }
    return result;
  }

  // `infrastructure`, not `access`: the `access` section is about *people*
  // (it is gated on iam:assign-role), while an SSH key, a bearer token and a
  // provider API token are credentials of the machines. The screen that shows
  // them is mounted under the infrastructure routes, not the access ones.
  @Delete('ssh-keys/:id')
  @RequireSection(SECTION.INFRASTRUCTURE)
  @ApiOperation({
    summary: 'Remove SSH key',
    description:
      'Deletes the SSH key from the local database. ' +
      'By default also removes it from all synced cloud providers. ' +
      'Set removeFromProviders=false to delete only locally.',
  })
  @ApiQuery({
    name: 'removeFromProviders',
    required: false,
    type: Boolean,
    description: 'Also remove from synced cloud providers (default: true)',
  })
  @ApiQuery({
    name: 'provider',
    required: false,
    enum: CloudProvider,
    description:
      'Required when deleting a key that exists only on the provider (not in DB)',
  })
  @ApiResponse({ status: 200, description: 'SSH key removed successfully' })
  async removeSSHKey(
    @Request() req,
    @Param('id') id: string,
    @Query('removeFromProviders') removeFromProviders?: string,
    @Query('provider') provider?: CloudProvider,
  ) {
    const shouldRemoveFromProviders = removeFromProviders !== 'false';
    return this.accessService.removeSSHKey(
      '',
      id,
      shouldRemoveFromProviders,
      provider,
    );
  }

  @Post('bearer')
  @ApiOperation({ summary: 'Generate bearer token for cloud provider' })
  @ApiResponse({
    status: 201,
    description: 'Bearer token generated successfully',
    type: BearerTokenDto,
  })
  async generateBearerToken(
    @Body() createBearerTokenDto: CreateBearerTokenDto,
  ): Promise<BearerTokenDto> {
    return this.accessService.generateBearerToken(
      createBearerTokenDto.provider,
      createBearerTokenDto,
    );
  }

  @Post('bearer/refresh')
  @ApiOperation({ summary: 'Refresh bearer token' })
  @HttpCode(HttpStatus.OK)
  @ApiResponse({
    status: 200,
    description: 'Bearer token refreshed successfully',
    type: BearerTokenDto,
  })
  async refreshToken(@Body() dto: ProviderRefreshTokenDto) {
    return this.accessService.refreshBearerToken(dto.provider, dto);
  }

  @Get('bearer')
  @ApiOperation({ summary: 'List all bearer tokens' })
  @ApiResponse({
    status: 200,
    description: 'Returns all bearer tokens',
    type: [BearerTokenDto],
  })
  async listBearerTokens() {
    return await this.accessService.listBearerTokens();
  }

  @Delete('bearer/:id')
  @RequireSection(SECTION.INFRASTRUCTURE)
  @ApiOperation({ summary: 'Remove bearer token' })
  @ApiResponse({
    status: 200,
    description: 'Bearer token removed successfully',
  })
  async removeBearerToken(@Param('id') id: string) {
    return await this.accessService.removeBearerToken(id);
  }

  @Get('api-tokens')
  @ApiOperation({ summary: 'List all stored API tokens' })
  @ApiResponse({
    status: 200,
    description: 'Returns all stored API tokens',
    type: [ApiTokenDto],
  })
  async listApiTokens() {
    return await this.accessService.listApiTokens();
  }

  @Post('api-tokens')
  @ApiOperation({ summary: 'Store API token from external provider' })
  @ApiResponse({
    status: 201,
    description: 'API token stored successfully',
    type: ApiTokenDto,
  })
  async createApiToken(@Body() createApiTokenDto: CreateApiTokenDto) {
    return await this.accessService.createApiToken(createApiTokenDto);
  }

  @Get('api-tokens/:id')
  @ApiOperation({ summary: 'Get API token information by ID' })
  @ApiResponse({
    status: 200,
    description: 'Returns the API token information without the token value',
    type: ApiTokenDto,
  })
  async getApiToken(@Param('id') id: string) {
    return await this.accessService.getApiToken(id);
  }

  @Delete('api-tokens/:id')
  @RequireSection(SECTION.INFRASTRUCTURE)
  @ApiOperation({ summary: 'Remove stored API token' })
  @ApiResponse({
    status: 200,
    description: 'API token removed successfully',
  })
  async removeApiToken(@Param('id') id: string) {
    return await this.accessService.removeApiToken(id);
  }
}
