/**
 * Read-only command classification for the key-value console. The console runs in read-only
 * mode by default: any command NOT in this set is treated as a write and rejected unless the
 * operator turns read-only off (mirrors the SQL read-only transaction gate). Unknown commands
 * default to write — fail safe.
 */
const READ_ONLY_COMMANDS = new Set<string>([
  // server / keyspace introspection
  'PING',
  'ECHO',
  'INFO',
  'DBSIZE',
  'TIME',
  'TYPE',
  'TTL',
  'PTTL',
  'EXISTS',
  'KEYS',
  'SCAN',
  'RANDOMKEY',
  'OBJECT',
  'MEMORY',
  'DUMP',
  'TOUCH',
  // strings
  'GET',
  'GETRANGE',
  'MGET',
  'STRLEN',
  'SUBSTR',
  'BITCOUNT',
  'GETBIT',
  'BITPOS',
  // hashes
  'HGET',
  'HMGET',
  'HGETALL',
  'HKEYS',
  'HVALS',
  'HLEN',
  'HEXISTS',
  'HSTRLEN',
  'HSCAN',
  'HRANDFIELD',
  // lists
  'LRANGE',
  'LLEN',
  'LINDEX',
  'LPOS',
  // sets
  'SMEMBERS',
  'SCARD',
  'SISMEMBER',
  'SMISMEMBER',
  'SRANDMEMBER',
  'SSCAN',
  'SINTER',
  'SUNION',
  'SDIFF',
  // sorted sets
  'ZRANGE',
  'ZRANGEBYSCORE',
  'ZRANGEBYLEX',
  'ZREVRANGE',
  'ZCARD',
  'ZCOUNT',
  'ZSCORE',
  'ZMSCORE',
  'ZRANK',
  'ZREVRANK',
  'ZSCAN',
  'ZRANDMEMBER',
  // streams (read)
  'XLEN',
  'XRANGE',
  'XREVRANGE',
  'XINFO',
  'XREAD',
  // geo / bitmap reads
  'GEOPOS',
  'GEODIST',
  'GEOSEARCH',
]);

export function isReadOnlyCommand(name: string): boolean {
  return READ_ONLY_COMMANDS.has(name.trim().toUpperCase());
}

// Common write/admin commands — together with the read set this lets us recognize a Redis
// command line in free-form model output (when the model ignored the JSON contract).
const WRITE_COMMANDS = new Set<string>([
  'SET',
  'SETEX',
  'PSETEX',
  'SETNX',
  'MSET',
  'MSETNX',
  'GETSET',
  'GETDEL',
  'APPEND',
  'SETBIT',
  'SETRANGE',
  'INCR',
  'INCRBY',
  'INCRBYFLOAT',
  'DECR',
  'DECRBY',
  'DEL',
  'UNLINK',
  'EXPIRE',
  'PEXPIRE',
  'EXPIREAT',
  'PERSIST',
  'RENAME',
  'RENAMENX',
  'COPY',
  'MOVE',
  'RESTORE',
  'HSET',
  'HMSET',
  'HSETNX',
  'HDEL',
  'HINCRBY',
  'HINCRBYFLOAT',
  'LPUSH',
  'LPUSHX',
  'RPUSH',
  'RPUSHX',
  'LPOP',
  'RPOP',
  'LSET',
  'LREM',
  'LINSERT',
  'LTRIM',
  'RPOPLPUSH',
  'SADD',
  'SREM',
  'SPOP',
  'SMOVE',
  'SINTERSTORE',
  'SUNIONSTORE',
  'SDIFFSTORE',
  'ZADD',
  'ZREM',
  'ZINCRBY',
  'ZPOPMIN',
  'ZPOPMAX',
  'ZREMRANGEBYRANK',
  'ZREMRANGEBYSCORE',
  'XADD',
  'XDEL',
  'XTRIM',
  'GEOADD',
  'FLUSHALL',
  'FLUSHDB',
]);

export function isKnownRedisCommand(name: string): boolean {
  const n = name.trim().toUpperCase();
  return READ_ONLY_COMMANDS.has(n) || WRITE_COMMANDS.has(n);
}
