// src/modules/access/repositories/default-access.repository.ts
import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { SSHKeyEntity } from '../entities/ssh-key.entity';
import { IAccessRepository } from '../interfaces/access.repository';
import {
  SSHKey,
  SSHKeyInput,
  SSHKeyPair,
} from '../interfaces/ssh-key.interface';

@Injectable()
export class DefaultAccessRepository implements IAccessRepository {
  constructor(
    @InjectRepository(SSHKeyEntity)
    private readonly sshKeyRepo: Repository<SSHKeyEntity>,
  ) {}

  async findAllKeys(
    tagFilters?: Record<string, string | string[]>,
  ): Promise<SSHKey[]> {
    const query = this.sshKeyRepo
      .createQueryBuilder('ssh_key')
      .where('ssh_key.isActive = :isActive', { isActive: true });

    // Apply tag filters if present
    if (tagFilters && Object.keys(tagFilters).length > 0) {
      const conditions: string[] = [];
      const parameters: any = {};

      Object.entries(tagFilters).forEach(([key, value], index) => {
        if (Array.isArray(value)) {
          // For array filters: find keys that have AT LEAST ONE of the values
          // tags->'cluster-id' ?| array['val1', 'val2']
          conditions.push(`ssh_key.tags->'${key}' ?| :array${index}`);
          parameters[`array${index}`] = value;
        } else {
          // For string filters: can match direct string OR be contained in array
          conditions.push(`(
            ssh_key.tags->>'${key}' = :value${index}
            OR ssh_key.tags->'${key}' ? :value${index}
          )`);
          parameters[`value${index}`] = value;
        }
      });

      if (conditions.length > 0) {
        query.andWhere(`(${conditions.join(' AND ')})`, parameters);
      }
    }

    const entities = await query.getMany();
    return entities as SSHKey[];
  }

  async findKeyById(id: string): Promise<SSHKey | null> {
    const entity = await this.sshKeyRepo.findOneBy({ id });
    return entity as SSHKey | null;
  }

  async findKeyByFingerprint(fingerprint: string): Promise<SSHKey | null> {
    const entity = await this.sshKeyRepo.findOneBy({ fingerprint });
    return entity as SSHKey | null;
  }

  async findKeyByProviderKeyId(providerKeyId: string): Promise<SSHKey | null> {
    const entity = await this.sshKeyRepo
      .createQueryBuilder('ssh_key')
      .where(`ssh_key."providerKeyMappings"::text LIKE :pattern`, {
        pattern: `%"${providerKeyId}"%`,
      })
      .getOne();
    return entity as SSHKey | null;
  }

  async createKey(
    keyInput: SSHKeyInput,
    keyPair: SSHKeyPair,
    tags?: Record<string, string | string[]>,
    autoGenerated?: boolean,
  ): Promise<SSHKey> {
    const sshKey = this.sshKeyRepo.create({
      name: keyInput.name,
      type: keyInput.type || 'ed25519',
      publicKey: keyPair.publicKey,
      fingerprint: keyPair.fingerprint,
      keyPath: keyPair.privateKey,
      sealedPrivateKey: keyPair.sealedPrivateKey ?? null,
      isActive: true,
      autoGenerated: autoGenerated || false,
      tags: tags || {},
      providerKeyMappings: {},
    });

    const savedEntity = await this.sshKeyRepo.save(sshKey);
    return savedEntity as SSHKey;
  }

  async deleteKey(id: string): Promise<void> {
    await this.sshKeyRepo.update(id, { isActive: false });
  }

  async updateKeyLastUsed(id: string): Promise<SSHKey> {
    const entity = await this.sshKeyRepo.findOneBy({ id });
    if (!entity) {
      throw new Error('SSH key not found');
    }

    entity.lastUsed = new Date();
    const updatedEntity = await this.sshKeyRepo.save(entity);
    return updatedEntity as SSHKey;
  }

  async updateKey(
    id: string,
    updates: Partial<SSHKey>,
  ): Promise<SSHKey | null> {
    const entity = await this.sshKeyRepo.findOneBy({ id });
    if (!entity) {
      return null;
    }

    // Update only provided fields
    if (updates.tags !== undefined) {
      entity.tags = updates.tags;
    }

    if (updates.providerKeyMappings !== undefined) {
      entity.providerKeyMappings = updates.providerKeyMappings;
    }

    if (updates.sealedPrivateKey !== undefined) {
      entity.sealedPrivateKey = updates.sealedPrivateKey;
    }

    const updatedEntity = await this.sshKeyRepo.save(entity);
    return updatedEntity as SSHKey;
  }
}
