import type { ProfileKey } from './vault-crypto';

export const SUPPLIED_KEY_VAR = 'FLUI_PROFILE_KEY';

/**
 * A profile key handed to the CLI by whoever started it — 32 bytes, base64.
 *
 * The vault assumes a home directory that outlives the command and an operator
 * who can type a passphrase. Some callers have neither: a provisioning worker
 * gives each run its own HOME and destroys it when the run ends. Prompting
 * there is impossible, and falling back to a key file would put the key inside
 * the very directory it protects — which is the arrangement the vault exists to
 * remove.
 *
 * Supplied this way the key lives in the caller's memory. Whatever the run
 * sealed on disk stops being openable the moment the caller forgets it, so an
 * abandoned directory is inert rather than merely deleted.
 *
 * A value that is present but malformed is an error, never a quiet fallback.
 * The caller meant to supply a key; a CLI that carried on regardless would seal
 * the run's credentials under something the caller cannot reproduce, and the
 * failure would surface later as an undecryptable profile.
 */
export function suppliedProfileKey(
  env: NodeJS.ProcessEnv = process.env,
): ProfileKey | null {
  const raw = env[SUPPLIED_KEY_VAR]?.trim();
  if (!raw) return null;

  // Accept base64url too: a key generated with `openssl rand -base64` and one
  // generated by a URL-safe encoder are the same 32 bytes.
  const normalised = raw
    .replace(/-/g, '+')
    .replace(/_/g, '/')
    .replace(/=+$/, '');
  const key = Buffer.from(normalised, 'base64');

  if (
    key.length !== 32 ||
    key.toString('base64').replace(/=+$/, '') !== normalised
  ) {
    throw new Error(
      `${SUPPLIED_KEY_VAR} is not a valid key: it must be 32 bytes, base64-encoded.\n` +
        '  Generate one with:  openssl rand -base64 32',
    );
  }
  return key as ProfileKey;
}
