export interface SSHKey {
  id: string;
  name: string;
  publicKey: string;
  fingerprint: string;
  keyPath: string;
  sealedPrivateKey?: string | null;
  type: 'ed25519' | 'rsa';
  isActive: boolean;
  autoGenerated: boolean;
  lastUsed?: Date;
  createdAt: Date;
  updatedAt: Date;
  tags?: Record<string, string | string[]>;
  providerKeyMappings?: Record<string, string>;
}

export interface SSHKeyInput {
  name: string;
  userName: string;
  type?: 'ed25519' | 'rsa';
  tags?: Record<string, string | string[]>;
}

export interface SSHKeyPair {
  publicKey: string;
  privateKey: string;
  fingerprint: string;
  sealedPrivateKey?: string;
}
